[server]
headless = true
port = 8501  # Remove a variável $PORT
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"

[theme]
primaryColor="#bd93f9"
backgroundColor="#282a36"
secondaryBackgroundColor="#44475a"
textColor="#f8f8f2"


